/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ebkyzljveylrerrmoctw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVia3l6bGp2ZXlscmVycm1vY3R3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMxMDEzNDQsImV4cCI6MjA3ODY3NzM0NH0.lyOtWqRtoY9n2NuS4vNWEl-kQWE7qm-5vJNGW0bkILU"